# Generated by Django 4.1.1 on 2023-01-05 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="hewan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama_biota", models.CharField(max_length=75)),
                (
                    "gambar",
                    models.ImageField(blank=True, null=True, upload_to="images/"),
                ),
                ("deskripsi", models.CharField(max_length=750)),
            ],
        ),
        migrations.CreateModel(
            name="kawasan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama_konservasi", models.CharField(max_length=75)),
                ("lintang", models.FloatField(null=True)),
                ("bujur", models.FloatField(null=True)),
            ],
        ),
    ]
